/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PortalSettings = {
  _id: string;
  _type: "portalSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationRecipients: Array<string>;
  fromName: string;
  fromEmail: string;
  replyToEmail?: string;
  portalUrl: string;
  supportEmail?: string;
  scopeBoundaryNote?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail: string;
  contactPhone?: string;
  address?: string;
  businessAddress?: {
    streetAddress?: string;
    suburb?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  portalUrl?: string;
  meetingsUrl: string;
  linkedInUrl?: string;
  instagramUrl?: string;
  youTubeUrl?: string;
  googleReviewCount?: number;
  happyClients?: number;
  hubspotReviewCount?: number;
  newsletterHeading?: string;
  defaultSeo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  pastHeading?: string;
  pastIntro?: string;
  emptyHeading?: string;
  emptyText?: string;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type CtaBanner = {
  _type: "ctaBanner";
  heading: string;
  text?: string;
  button: Link;
  showMeetingsEmbed?: boolean;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading: string;
  emphasisPhrase?: string;
  markerStyle?: "circle" | "underline" | "none";
  subheading?: string;
  videoUrl?: string;
  image?: ImageWithAlt;
  primaryCta?: Link;
  secondaryCta?: Link;
};

export type CareersPage = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilt?: boolean;
  hero?: Hero;
  storyRows?: Array<{
    eyebrow: string;
    body: string;
    image: ImageWithAlt;
    imagePosition?: "left" | "right";
    _type: "storyRow";
    _key: string;
  }>;
  values?: Array<{
    label: string;
    body: string;
    _type: "valueBlock";
    _key: string;
  }>;
  valuesImage?: ImageWithAlt;
  whyIntro?: string;
  teamPhoto?: ImageWithAlt;
  benefits?: Array<
    {
      _key: string;
    } & Benefit
  >;
  lifeVideo?: VimeoEmbed;
  openRolesHeading?: string;
  emptyStateMessage: string;
  registerInterest?: {
    heading?: string;
    body?: string;
  };
  seo?: Seo;
};

export type VimeoEmbed = {
  _type: "vimeoEmbed";
  url: string;
  title: string;
  orientation: "landscape" | "portrait" | "square";
  posterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  displayWidth?: number;
  displayHeight?: number;
  alt: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  formHeading?: string;
  formOptions?: Array<string>;
  successHeading?: string;
  successText?: string;
  detailsHeading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type InsightHubPage = {
  _id: string;
  _type: "insightHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  featuredPost?: BlogPostReference;
  resourcesHeading?: string;
  resources?: Array<{
    title: string;
    link?: Link;
    _type: "resourceCard";
    _key: string;
  }>;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type OurWorkPage = {
  _id: string;
  _type: "ourWorkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  videoTestimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  googleReviews?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  googleReviewsUrl?: string;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type IndustriesHubPage = {
  _id: string;
  _type: "industriesHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  industries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  whyHeading?: string;
  whyItems?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustPillars?: Array<{
    heading: string;
    text: string;
    image?: ImageWithAlt;
    _type: "pillarRow";
    _key: string;
  }>;
  teamHeading?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  culturePhotos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  cultureText?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  clientLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  storyVideoUrl?: string;
  storyHeading?: string;
  storyBody?: BlockContent;
  storyImage?: ImageWithAlt;
  lovePillars?: Array<
    {
      _key: string;
    } & IconCard
  >;
  values?: Array<
    {
      _key: string;
    } & IconCard
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "figure";
      _key: string;
    }
>;

export type SolutionsPage = {
  _id: string;
  _type: "solutionsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  carouselHeading?: string;
  carouselIntro?: string;
  optimiseHeading?: string;
  optimiseIntro?: string;
  optimiseCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  relatedCaseStudy?: CaseStudyReference;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ServicesLandingPage = {
  _id: string;
  _type: "servicesLandingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  serviceCards?: Array<{
    service: ServiceReference;
    titleOverride?: string;
    descriptionOverride?: string;
    categoryOverride?: "discover" | "build" | "scale";
    anchor?: string;
    _type: "serviceCard";
    _key: string;
  }>;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  testimonial?: TestimonialReference;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  introImages?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  featuredCaseStudy?: CaseStudyReference;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  featuredIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to: string;
  permanent?: boolean;
  reason?: string;
  createdAt?: string;
};

export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilt?: boolean;
  hero: Hero;
  valueProps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  proofStat?: Stat;
  testimonial?: TestimonialReference;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  formHeading?: string;
  formBody?: string;
  campaignName?: string;
  successHeading?: string;
  successBody?: string;
  seo?: Seo;
};

export type Stat = {
  _type: "stat";
  value: string;
  label: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Vacancy = {
  _id: string;
  _type: "vacancy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  status: "open" | "closed";
  workArrangement: "onSite" | "hybrid" | "remote";
  employmentType: "fullTime" | "partTime" | "contract" | "internship";
  location: string;
  department?: "delivery" | "marketing" | "operations" | "engineering";
  summary: string;
  description: BlockContent;
  responsibilities: Array<string>;
  requirements: Array<string>;
  niceToHave?: Array<string>;
  benefitsOverride?: Array<
    {
      _key: string;
    } & Benefit
  >;
  salaryMin?: number;
  salaryMax?: number;
  salaryCurrency?: string;
  salaryPeriod?: "YEAR" | "MONTH" | "HOUR";
  publishedAt: string;
  validThrough?: string;
  seo?: Seo;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clientName: string;
  slug: Slug;
  clientLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  engagementType: "project" | "retainer";
  retainerHoursPerMonth?: number;
  startDate: string;
  endDate?: string;
  portalStatus: "active" | "suspended" | "archived";
  emailDomains: Array<string>;
  stakeholders?: Array<
    {
      _key: string;
    } & Stakeholder
  >;
  zippilySpecialists?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  pointOfContact?: TeamMemberReference;
  meetingLink?: string;
  asanaPortfolioId: string;
  asanaLegacyProjectIds?: Array<string>;
  hubspotCompanyId?: string;
  xeroContactId?: string;
  hubspotLicensing?: HubspotLicensing;
  billingDayOfMonth: number;
  billingNotes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  portalWelcomeNote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  goals?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  challenges?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  recommendations?: Array<
    {
      _key: string;
    } & Recommendation
  >;
  featureSuggestions?: Array<
    {
      _key: string;
    } & FeatureSuggestion
  >;
  meetingRecords?: Array<
    {
      _key: string;
    } & MeetingRecord
  >;
};

export type HubOfferingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hubOffering";
};

export type HubspotLicensing = {
  _type: "hubspotLicensing";
  hubs?: Array<
    {
      _key: string;
    } & HubOfferingReference
  >;
  tier?: "free" | "starter" | "professional" | "enterprise";
  seats?: number;
  renewalDate?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body: BlockContent;
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  categories: Array<string>;
  startDateTime: string;
  endDateTime: string;
  venueType: "in-person" | "online";
  venueName?: string;
  address?: string;
  shortLocation?: string;
  geo?: Geopoint;
  platform?: string;
  heroImage?: ImageWithAlt;
  cardImage?: ImageWithAlt;
  shortDescription: string;
  description?: BlockContent;
  whatToExpect?: Array<{
    heading: string;
    body: string;
    _type: "expectItem";
    _key: string;
  }>;
  host: TeamMemberReference;
  hostIntro?: string;
  capacity: number;
  spotsRemaining: number;
  registrationClosesAt?: string;
  price?: number;
  recap?: BlogPostReference;
  seo?: Seo;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summaryBullets?: Array<string>;
  updatedAt: string;
  readTimeMinutes: number;
  fileAsset?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  landingPageHref?: string;
  author: TeamMemberReference;
  category?:
    | "feature-spotlights"
    | "best-practices"
    | "news-and-events"
    | "our-approach"
    | "ai-developments";
  relatedPost?: BlogPostReference;
  order: number;
  seo?: Seo;
};

export type Popup = {
  _id: string;
  _type: "popup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  enabled?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heading: string;
  body?: string;
  mode: "form" | "cta";
  buttonLabel: string;
  ctaHref?: string;
  successMessage?: string;
  triggerType: "exitIntent" | "timeOnPage" | "scrollDepth";
  triggerSeconds?: number;
  triggerPercent?: number;
  showAgainAfterDays?: number;
  includePaths?: Array<string>;
  excludePaths?: Array<string>;
};

export type PartnerIntegration = {
  _id: string;
  _type: "partnerIntegration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilt?: boolean;
  hero: Hero;
  whatItDoes?: BlockContent;
  whatWeSetUp?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudy?: CaseStudyReference;
  testimonial?: TestimonialReference;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  topic:
    | "feature-spotlights"
    | "best-practices"
    | "news-and-events"
    | "our-approach"
    | "ai-developments";
  hubs?: Array<
    {
      _key: string;
    } & HubOfferingReference
  >;
  author: TeamMemberReference;
  publishedAt: string;
  readTime: number;
  excerpt: string;
  coverImage: ImageWithAlt;
  dek?: string;
  shortVersion?: Array<string>;
  body: BlockContent;
  seo?: Seo;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  pronouns?: string;
  photo?: ImageWithAlt;
  bio?: string;
  outsideWork?: string;
  skills?: Array<string>;
  favouriteHubSpotFeature?: string;
  whyTheyLoveHubSpot?: string;
  linkedIn?: string;
  order?: number;
};

export type MeetingRecord = {
  _type: "meetingRecord";
  meetingDate: string;
  title: string;
  summary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  recordingUrl?: string;
  attendees?: Array<string>;
};

export type FeatureSuggestion = {
  _type: "featureSuggestion";
  featureName: string;
  relatedHub?: HubOfferingReference;
  howItWorks?: string;
  whyWeSuggestIt?: string;
  priority?: "high" | "medium" | "low";
};

export type HubOffering = {
  _id: string;
  _type: "hubOffering";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  eyebrow: string;
  description: string;
  icon?: string;
  linkedService: ServiceReference;
  isFeatured?: boolean;
  order: number;
};

export type PricingTableReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pricingTable";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "discover" | "build" | "scale";
  icon?: string;
  shortDescription: string;
  whoItsFor?: string;
  pageBuilt?: boolean;
  hero: Hero;
  heroMeta?: string;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  painPointsCloser?: string;
  processSteps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  pricingTable?: PricingTableReference;
  pricing?: Pricing;
  caseStudy?: CaseStudyReference;
  proofStat?: Stat;
  testimonial?: TestimonialReference;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: string;
  slug: Slug;
  status: "live" | "comingSoon";
  pageBuilt?: boolean;
  service: ServiceReference;
  industry?: IndustryReference;
  headline: string;
  resultLine?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  photo?: ImageWithAlt;
  videoUrl?: string;
  videoTestimonial?: VimeoEmbed;
  testimonial?: TestimonialReference;
  clientLogo?: ImageWithAlt;
  aboutImage?: ImageWithAlt;
  aboutBody?: string;
  challengeItems?: Array<{
    heading?: string;
    text?: string;
    _type: "storyItem";
    _key: string;
  }>;
  solutionItems?: Array<{
    heading?: string;
    text?: string;
    _type: "storyItem";
    _key: string;
  }>;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  resultsText?: string;
  resultsBullets?: Array<string>;
  fullBleedPhoto?: ImageWithAlt;
  body?: BlockContent;
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  icon?: string;
  shortDescription: string;
  pageBuilt?: boolean;
  hero?: Hero;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  howWeFixHeading?: string;
  howWeFixBody?: BlockContent;
  checklist?: Array<string>;
  caseStudy?: CaseStudyReference;
  proofStat?: Stat;
  testimonial?: TestimonialReference;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  role?: string;
  company: string;
  avatar?: ImageWithAlt;
  source?: "direct" | "google" | "hubspot";
  videoUrl?: string;
  videoStill?: ImageWithAlt;
};

export type Pricing = {
  _type: "pricing";
  confirmed?: boolean;
  tiers?: Array<
    {
      _key: string;
    } & PricingTier
  >;
  fallbackText?: string;
};

export type PricingTable = {
  _id: string;
  _type: "pricingTable";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  service?: ServiceReference;
  confirmed?: boolean;
  tiers?: Array<
    {
      _key: string;
    } & PricingTier
  >;
  fallbackText?: string;
  internalNote?: string;
};

export type Recommendation = {
  _type: "recommendation";
  title: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  horizon: "shortTerm" | "longTerm";
  status: "proposed" | "accepted" | "declined" | "done";
  dateAdded: string;
};

export type Stakeholder = {
  _type: "stakeholder";
  fullName: string;
  email: string;
  role?: string;
  isPortalAdmin?: boolean;
};

export type Benefit = {
  _type: "benefit";
  icon: string;
  heading: string;
  body: string;
};

export type IconCard = {
  _type: "iconCard";
  title: string;
  text: string;
  icon?: string;
};

export type PricingTier = {
  _type: "pricingTier";
  name: string;
  description?: string;
  custom?: boolean;
  price?: number;
  priceSuffix?: string;
  features?: Array<string>;
  ctaLabel?: string;
  featured?: boolean;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | PortalSettings
  | SiteSettings
  | SanityImageAssetReference
  | Seo
  | EventsPage
  | CtaBanner
  | Hero
  | CareersPage
  | VimeoEmbed
  | ImageWithAlt
  | ContactPage
  | BlogPostReference
  | InsightHubPage
  | Link
  | CaseStudyReference
  | TestimonialReference
  | OurWorkPage
  | IndustryReference
  | IndustriesHubPage
  | TeamMemberReference
  | AboutPage
  | BlockContent
  | SolutionsPage
  | ServiceReference
  | ServicesLandingPage
  | HomePage
  | Redirect
  | LandingPage
  | Stat
  | Slug
  | Vacancy
  | Client
  | HubOfferingReference
  | HubspotLicensing
  | SanityImageCrop
  | SanityImageHotspot
  | LegalPage
  | Event
  | Geopoint
  | SanityFileAssetReference
  | Resource
  | Popup
  | PartnerIntegration
  | BlogPost
  | TeamMember
  | MeetingRecord
  | FeatureSuggestion
  | HubOffering
  | PricingTableReference
  | Service
  | CaseStudy
  | Industry
  | Testimonial
  | Pricing
  | PricingTable
  | Recommendation
  | Stakeholder
  | Benefit
  | IconCard
  | PricingTier
  | FaqItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: ../web/app/sitemap.ts
// Variable: SITEMAP_QUERY
// Query: {    "services": *[_type == "service" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "platforms": *[_type == "partnerIntegration" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "industries": *[_type == "industry" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "caseStudies": *[_type == "caseStudy" && defined(slug.current) && status == "live" && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "posts": *[_type == "blogPost" && defined(slug.current)]{ "slug": slug.current, _updatedAt },    "events": *[_type == "event" && defined(slug.current)]{ "slug": slug.current, _updatedAt },    "careersBuilt": *[_type == "careersPage"][0].pageBuilt,    "landingPages": *[_type == "landingPage" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "vacancies": *[_type == "vacancy" && status == "open" && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt }  }
export type SITEMAP_QUERY_RESULT = {
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  platforms: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  industries: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  caseStudies: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  events: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  careersBuilt: boolean | null;
  landingPages: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  vacancies: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Source: ../web/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail: string;
  contactPhone?: string;
  address?: string;
  businessAddress?: {
    streetAddress?: string;
    suburb?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  portalUrl?: string;
  meetingsUrl: string;
  linkedInUrl?: string;
  instagramUrl?: string;
  youTubeUrl?: string;
  googleReviewCount?: number;
  happyClients?: number;
  hubspotReviewCount?: number;
  newsletterHeading?: string;
  defaultSeo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    ...,    featuredServices[]->{_id, title, slug, icon, shortDescription, whoItsFor},    featuredCaseStudy->{_id, client, slug, headline, resultLine, stats, photo, videoUrl, service->{title}},    testimonials[]->{_id, quote, name, role, company, avatar},    featuredIndustries[]->{_id, title, slug, icon, shortDescription, pageBuilt}  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  introImages?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  featuredServices: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    whoItsFor: string | null;
  }> | null;
  featuredCaseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    stats: Array<
      {
        _key: string;
      } & Stat
    > | null;
    photo: ImageWithAlt | null;
    videoUrl: string | null;
    service: {
      title: string;
    };
  } | null;
  testimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  }> | null;
  featuredIndustries: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    pageBuilt: boolean | null;
  }> | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: SERVICES_LANDING_QUERY
// Query: *[_type == "servicesLandingPage"][0]{    ...,    serviceCards[]{      ...,      service->{_id, title, slug, category, icon, shortDescription, whoItsFor}    },    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},    testimonial->{_id, quote, name, role, company}  }
export type SERVICES_LANDING_QUERY_RESULT = {
  _id: string;
  _type: "servicesLandingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  serviceCards: Array<{
    service: {
      _id: string;
      title: string;
      slug: Slug;
      category: "build" | "discover" | "scale";
      icon: string | null;
      shortDescription: string;
      whoItsFor: string | null;
    };
    titleOverride?: string;
    descriptionOverride?: string;
    categoryOverride?: "build" | "discover" | "scale";
    anchor?: string;
    _type: "serviceCard";
    _key: string;
  }> | null;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  }> | null;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
  } | null;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    ...,    team[]->{_id, name, role, pronouns, photo, bio, outsideWork, skills, favouriteHubSpotFeature, whyTheyLoveHubSpot, linkedIn},    testimonials[]->{_id, quote, name, role, company, avatar}  }
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustPillars?: Array<{
    heading: string;
    text: string;
    image?: ImageWithAlt;
    _type: "pillarRow";
    _key: string;
  }>;
  teamHeading?: string;
  team: Array<{
    _id: string;
    name: string;
    role: string;
    pronouns: string | null;
    photo: ImageWithAlt | null;
    bio: string | null;
    outsideWork: string | null;
    skills: Array<string> | null;
    favouriteHubSpotFeature: string | null;
    whyTheyLoveHubSpot: string | null;
    linkedIn: string | null;
  }> | null;
  culturePhotos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  cultureText?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  testimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  }> | null;
  clientLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  storyVideoUrl?: string;
  storyHeading?: string;
  storyBody?: BlockContent;
  storyImage?: ImageWithAlt;
  lovePillars?: Array<
    {
      _key: string;
    } & IconCard
  >;
  values?: Array<
    {
      _key: string;
    } & IconCard
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  formHeading?: string;
  formOptions?: Array<string>;
  successHeading?: string;
  successText?: string;
  detailsHeading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc)[0...3]{    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,    hubs[]->{name}  }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  excerpt: string;
  coverImage: ImageWithAlt;
  publishedAt: string;
  readTime: number;
  hubs: Array<{
    name: string;
  }> | null;
}>;

// Source: ../web/sanity/queries.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service" && defined(slug.current)].slug.current
export type SERVICE_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    ...,    pricingTable->{confirmed, tiers, fallbackText},    caseStudy->{_id, client, slug, headline, resultLine, photo, status},    testimonial->{_id, quote, name, role, company, avatar},    relatedServices[]->{_id, title, slug, icon, shortDescription}  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "build" | "discover" | "scale";
  icon?: string;
  shortDescription: string;
  whoItsFor?: string;
  pageBuilt?: boolean;
  hero: Hero;
  heroMeta?: string;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  painPointsCloser?: string;
  processSteps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  pricingTable: {
    confirmed: boolean | null;
    tiers: Array<
      {
        _key: string;
      } & PricingTier
    > | null;
    fallbackText: string | null;
  } | null;
  pricing?: Pricing;
  caseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
  } | null;
  proofStat?: Stat;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  relatedServices: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
  }> | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: SOLUTIONS_PAGE_QUERY
// Query: *[_type == "solutionsPage"][0]{    ...,    relatedCaseStudy->{_id, client, slug, headline, resultLine, photo, status, service->{title}}  }
export type SOLUTIONS_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "solutionsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  carouselHeading?: string;
  carouselIntro?: string;
  optimiseHeading?: string;
  optimiseIntro?: string;
  optimiseCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  relatedCaseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  } | null;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: HUB_OFFERINGS_QUERY
// Query: *[_type == "hubOffering"] | order(order asc){    _id, name, eyebrow, description, icon, isFeatured,    linkedService->{title, slug}  }
export type HUB_OFFERINGS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  eyebrow: string;
  description: string;
  icon: string | null;
  isFeatured: boolean | null;
  linkedService: {
    title: string;
    slug: Slug;
  };
}>;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRIES_HUB_QUERY
// Query: *[_type == "industriesHubPage"][0]{    ...,    industries[]->{_id, title, slug, icon, shortDescription, pageBuilt},    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, industry->{title}}  }
export type INDUSTRIES_HUB_QUERY_RESULT = {
  _id: string;
  _type: "industriesHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  industries: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    pageBuilt: boolean | null;
  }> | null;
  whyHeading?: string;
  whyItems?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    industry: {
      title: string;
    } | null;
  }> | null;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRY_SLUGS_QUERY
// Query: *[_type == "industry" && defined(slug.current)].slug.current
export type INDUSTRY_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRY_QUERY
// Query: *[_type == "industry" && slug.current == $slug][0]{    ...,    caseStudy->{_id, client, slug, headline, resultLine, photo, status},    testimonial->{_id, quote, name, role, company, avatar}  }
export type INDUSTRY_QUERY_RESULT = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  icon?: string;
  shortDescription: string;
  pageBuilt?: boolean;
  hero?: Hero;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  howWeFixHeading?: string;
  howWeFixBody?: BlockContent;
  checklist?: Array<string>;
  caseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
  } | null;
  proofStat?: Stat;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: OUR_WORK_QUERY
// Query: *[_type == "ourWorkPage"][0]{    ...,    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},    videoTestimonials[]->{_id, quote, name, company, videoUrl, videoStill},    googleReviews[]->{_id, quote, name, company}  }
export type OUR_WORK_QUERY_RESULT = {
  _id: string;
  _type: "ourWorkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  }> | null;
  videoTestimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    company: string;
    videoUrl: string | null;
    videoStill: ImageWithAlt | null;
  }> | null;
  googleReviews: Array<{
    _id: string;
    quote: string;
    name: string;
    company: string;
  }> | null;
  googleReviewsUrl?: string;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    ...,    service->{title, slug},    industry->{title, slug},    testimonial->{_id, quote, name, role, company, avatar}  }
export type CASE_STUDY_QUERY_RESULT = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: string;
  slug: Slug;
  status: "comingSoon" | "live";
  pageBuilt?: boolean;
  service: {
    title: string;
    slug: Slug;
  };
  industry: {
    title: string;
    slug: Slug;
  } | null;
  headline: string;
  resultLine?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  photo?: ImageWithAlt;
  videoUrl?: string;
  videoTestimonial?: VimeoEmbed;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  clientLogo?: ImageWithAlt;
  aboutImage?: ImageWithAlt;
  aboutBody?: string;
  challengeItems?: Array<{
    heading?: string;
    text?: string;
    _type: "storyItem";
    _key: string;
  }>;
  solutionItems?: Array<{
    heading?: string;
    text?: string;
    _type: "storyItem";
    _key: string;
  }>;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  resultsText?: string;
  resultsBullets?: Array<string>;
  fullBleedPhoto?: ImageWithAlt;
  body?: BlockContent;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: RELATED_CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current) && slug.current != $slug]    | order(status desc, client asc)[0...3]{      _id, client, slug, resultLine, photo, status, service->{title}    }
export type RELATED_CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  client: string;
  slug: Slug;
  resultLine: string | null;
  photo: ImageWithAlt | null;
  status: "comingSoon" | "live";
  service: {
    title: string;
  };
}>;

// Source: ../web/sanity/queries.ts
// Variable: INSIGHT_HUB_QUERY
// Query: *[_type == "insightHubPage"][0]{    ...,    featuredPost->{      _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,      hubs[]->{name}, author->{name, photo}    }  }
export type INSIGHT_HUB_QUERY_RESULT = {
  _id: string;
  _type: "insightHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  featuredPost: {
    _id: string;
    title: string;
    slug: Slug;
    topic:
      | "ai-developments"
      | "best-practices"
      | "feature-spotlights"
      | "news-and-events"
      | "our-approach";
    excerpt: string;
    coverImage: ImageWithAlt;
    publishedAt: string;
    readTime: number;
    hubs: Array<{
      name: string;
    }> | null;
    author: {
      name: string;
      photo: ImageWithAlt | null;
    };
  } | null;
  resourcesHeading?: string;
  resources?: Array<{
    title: string;
    link?: Link;
    _type: "resourceCard";
    _key: string;
  }>;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc){    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,    hubs[]->{name}  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  excerpt: string;
  coverImage: ImageWithAlt;
  publishedAt: string;
  readTime: number;
  hubs: Array<{
    name: string;
  }> | null;
}>;

// Source: ../web/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: EVENTS_PAGE_QUERY
// Query: {    "page": *[_type == "eventsPage"][0],    "upcoming": *[_type == "event" && startDateTime >= now()] | order(startDateTime asc){        _id, title, slug, categories, startDateTime, endDateTime, venueType,  shortLocation, shortDescription, cardImage, capacity, spotsRemaining    },    "past": *[_type == "event" && startDateTime < now()] | order(startDateTime desc)[0...5]{        _id, title, slug, categories, startDateTime, endDateTime, venueType,  shortLocation, shortDescription, cardImage, capacity, spotsRemaining,      recap->{title, slug}    }  }
export type EVENTS_PAGE_QUERY_RESULT = {
  page: {
    _id: string;
    _type: "eventsPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    hero: Hero;
    pastHeading?: string;
    pastIntro?: string;
    emptyHeading?: string;
    emptyText?: string;
    ctaBanner?: CtaBanner;
    seo?: Seo;
  } | null;
  upcoming: Array<{
    _id: string;
    title: string;
    slug: Slug;
    categories: Array<string>;
    startDateTime: string;
    endDateTime: string;
    venueType: "in-person" | "online";
    shortLocation: string | null;
    shortDescription: string;
    cardImage: ImageWithAlt | null;
    capacity: number;
    spotsRemaining: number;
  }>;
  past: Array<{
    _id: string;
    title: string;
    slug: Slug;
    categories: Array<string>;
    startDateTime: string;
    endDateTime: string;
    venueType: "in-person" | "online";
    shortLocation: string | null;
    shortDescription: string;
    cardImage: ImageWithAlt | null;
    capacity: number;
    spotsRemaining: number;
    recap: {
      title: string;
      slug: Slug;
    } | null;
  }>;
};

// Source: ../web/sanity/queries.ts
// Variable: EVENT_SLUGS_QUERY
// Query: *[_type == "event" && defined(slug.current)].slug.current
export type EVENT_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: EVENT_QUERY
// Query: {    "event": *[_type == "event" && slug.current == $slug][0]{      ...,      host->{name, role, photo, linkedIn},      recap->{title, slug}    },    "others": *[_type == "event" && slug.current != $slug && startDateTime >= now()]      | order(startDateTime asc)[0...2]{   _id, title, slug, categories, startDateTime, endDateTime, venueType,  shortLocation, shortDescription, cardImage, capacity, spotsRemaining }  }
export type EVENT_QUERY_RESULT = {
  event: {
    _id: string;
    _type: "event";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    categories: Array<string>;
    startDateTime: string;
    endDateTime: string;
    venueType: "in-person" | "online";
    venueName?: string;
    address?: string;
    shortLocation?: string;
    geo?: Geopoint;
    platform?: string;
    heroImage?: ImageWithAlt;
    cardImage?: ImageWithAlt;
    shortDescription: string;
    description?: BlockContent;
    whatToExpect?: Array<{
      heading: string;
      body: string;
      _type: "expectItem";
      _key: string;
    }>;
    host: {
      name: string;
      role: string;
      photo: ImageWithAlt | null;
      linkedIn: string | null;
    };
    hostIntro?: string;
    capacity: number;
    spotsRemaining: number;
    registrationClosesAt?: string;
    price?: number;
    recap: {
      title: string;
      slug: Slug;
    } | null;
    seo?: Seo;
  } | null;
  others: Array<{
    _id: string;
    title: string;
    slug: Slug;
    categories: Array<string>;
    startDateTime: string;
    endDateTime: string;
    venueType: "in-person" | "online";
    shortLocation: string | null;
    shortDescription: string;
    cardImage: ImageWithAlt | null;
    capacity: number;
    spotsRemaining: number;
  }>;
};

// Source: ../web/sanity/queries.ts
// Variable: RESOURCES_QUERY
// Query: *[_type == "resource"] | order(order asc){    _id, title, slug, summaryBullets, updatedAt, readTimeMinutes,    landingPageHref, category,    "fileUrl": fileAsset.asset->url,    author->{name, photo},    relatedPost->{title, slug}  }
export type RESOURCES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summaryBullets: Array<string> | null;
  updatedAt: string;
  readTimeMinutes: number;
  landingPageHref: string | null;
  category:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach"
    | null;
  fileUrl: string | null;
  author: {
    name: string;
    photo: ImageWithAlt | null;
  };
  relatedPost: {
    title: string;
    slug: Slug;
  } | null;
}>;

// Source: ../web/sanity/queries.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && slug.current == $slug][0]
export type LEGAL_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body: BlockContent;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: PARTNER_INTEGRATION_QUERY
// Query: *[_type == "partnerIntegration" && slug.current == $slug][0]{    ...,    caseStudy->{_id, client, slug, headline, resultLine, photo, status},    testimonial->{_id, quote, name, role, company, avatar}  }
export type PARTNER_INTEGRATION_QUERY_RESULT = {
  _id: string;
  _type: "partnerIntegration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilt?: boolean;
  hero: Hero;
  whatItDoes?: BlockContent;
  whatWeSetUp?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
  } | null;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: PARTNER_INTEGRATION_SLUGS_QUERY
// Query: *[_type == "partnerIntegration" && defined(slug.current)].slug.current
export type PARTNER_INTEGRATION_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0]{    ...,    hubs[]->{name},    author->{name, role, photo},    "related": *[_type == "blogPost" && slug.current != $slug] | order(publishedAt desc)[0...3]{      _id, title, slug, topic, coverImage, publishedAt, readTime    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  hubs: Array<{
    name: string;
  }> | null;
  author: {
    name: string;
    role: string;
    photo: ImageWithAlt | null;
  };
  publishedAt: string;
  readTime: number;
  excerpt: string;
  coverImage: ImageWithAlt;
  dek?: string;
  shortVersion?: Array<string>;
  body: BlockContent;
  seo?: Seo;
  related: Array<{
    _id: string;
    title: string;
    slug: Slug;
    topic:
      | "ai-developments"
      | "best-practices"
      | "feature-spotlights"
      | "news-and-events"
      | "our-approach";
    coverImage: ImageWithAlt;
    publishedAt: string;
    readTime: number;
  }>;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: CAREERS_PAGE_QUERY
// Query: *[_type == "careersPage"][0]{    ...,    "openRoles": *[_type == "vacancy" && status == "open" && defined(slug.current)]      | order(publishedAt desc){        _id, title, slug, summary, workArrangement, employmentType, location, department      }  }
export type CAREERS_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilt?: boolean;
  hero?: Hero;
  storyRows?: Array<{
    eyebrow: string;
    body: string;
    image: ImageWithAlt;
    imagePosition?: "left" | "right";
    _type: "storyRow";
    _key: string;
  }>;
  values?: Array<{
    label: string;
    body: string;
    _type: "valueBlock";
    _key: string;
  }>;
  valuesImage?: ImageWithAlt;
  whyIntro?: string;
  teamPhoto?: ImageWithAlt;
  benefits?: Array<
    {
      _key: string;
    } & Benefit
  >;
  lifeVideo?: VimeoEmbed;
  openRolesHeading?: string;
  emptyStateMessage: string;
  registerInterest?: {
    heading?: string;
    body?: string;
  };
  seo?: Seo;
  openRoles: Array<{
    _id: string;
    title: string;
    slug: Slug;
    summary: string;
    workArrangement: "hybrid" | "onSite" | "remote";
    employmentType: "contract" | "fullTime" | "internship" | "partTime";
    location: string;
    department: "delivery" | "engineering" | "marketing" | "operations" | null;
  }>;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: VACANCY_QUERY
// Query: *[_type == "vacancy" && slug.current == $slug][0]{    ...,    "sharedBenefits": *[_type == "careersPage"][0].benefits,    "teamPhoto": *[_type == "careersPage"][0].teamPhoto,    "registerInterest": *[_type == "careersPage"][0].registerInterest,    "related": *[_type == "vacancy" && status == "open" && slug.current != $slug]      | order(publishedAt desc)[0...3]{        _id, title, slug, summary, workArrangement, employmentType, location      }  }
export type VACANCY_QUERY_RESULT = {
  _id: string;
  _type: "vacancy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  status: "closed" | "open";
  workArrangement: "hybrid" | "onSite" | "remote";
  employmentType: "contract" | "fullTime" | "internship" | "partTime";
  location: string;
  department?: "delivery" | "engineering" | "marketing" | "operations";
  summary: string;
  description: BlockContent;
  responsibilities: Array<string>;
  requirements: Array<string>;
  niceToHave?: Array<string>;
  benefitsOverride?: Array<
    {
      _key: string;
    } & Benefit
  >;
  salaryMin?: number;
  salaryMax?: number;
  salaryCurrency?: string;
  salaryPeriod?: "HOUR" | "MONTH" | "YEAR";
  publishedAt: string;
  validThrough?: string;
  seo?: Seo;
  sharedBenefits: Array<
    {
      _key: string;
    } & Benefit
  > | null;
  teamPhoto: ImageWithAlt | null;
  registerInterest: {
    heading?: string;
    body?: string;
  } | null;
  related: Array<{
    _id: string;
    title: string;
    slug: Slug;
    summary: string;
    workArrangement: "hybrid" | "onSite" | "remote";
    employmentType: "contract" | "fullTime" | "internship" | "partTime";
    location: string;
  }>;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: VACANCY_SLUGS_QUERY
// Query: *[_type == "vacancy" && defined(slug.current)].slug.current
export type VACANCY_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: OPEN_VACANCY_SLUGS_QUERY
// Query: *[_type == "vacancy" && status == "open" && defined(slug.current)]{    "slug": slug.current, _updatedAt  }
export type OPEN_VACANCY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../web/sanity/queries.ts
// Variable: LANDING_PAGE_QUERY
// Query: *[_type == "landingPage" && slug.current == $slug][0]{    ...,    testimonial->{_id, quote, name, role, company, avatar}  }
export type LANDING_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilt?: boolean;
  hero: Hero;
  valueProps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  proofStat?: Stat;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  formHeading?: string;
  formBody?: string;
  campaignName?: string;
  successHeading?: string;
  successBody?: string;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: LANDING_PAGE_SLUGS_QUERY
// Query: *[_type == "landingPage" && defined(slug.current)].slug.current
export type LANDING_PAGE_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: BUILT_LANDING_PAGES_QUERY
// Query: *[_type == "landingPage" && defined(slug.current) && pageBuilt == true]{    "slug": slug.current, _updatedAt  }
export type BUILT_LANDING_PAGES_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../web/sanity/queries.ts
// Variable: POPUP_QUERY
// Query: *[_type == "popup" && enabled == true]|order(_updatedAt desc)[0]{    _id, heading, body, mode, buttonLabel, ctaHref, successMessage,    triggerType, triggerSeconds, triggerPercent, showAgainAfterDays,    includePaths, excludePaths,    "imageUrl": image.asset->url,    "imageAlt": image.alt  }
export type POPUP_QUERY_RESULT = {
  _id: string;
  heading: string;
  body: string | null;
  mode: "cta" | "form";
  buttonLabel: string;
  ctaHref: string | null;
  successMessage: string | null;
  triggerType: "exitIntent" | "scrollDepth" | "timeOnPage";
  triggerSeconds: number | null;
  triggerPercent: number | null;
  showAgainAfterDays: number | null;
  includePaths: Array<string> | null;
  excludePaths: Array<string> | null;
  imageUrl: string | null;
  imageAlt: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n    "services": *[_type == "service" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "platforms": *[_type == "partnerIntegration" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "industries": *[_type == "industry" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "caseStudies": *[_type == "caseStudy" && defined(slug.current) && status == "live" && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "posts": *[_type == "blogPost" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n    "events": *[_type == "event" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n    "careersBuilt": *[_type == "careersPage"][0].pageBuilt,\n    "landingPages": *[_type == "landingPage" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "vacancies": *[_type == "vacancy" && status == "open" && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt }\n  }': SITEMAP_QUERY_RESULT;
    '*[_type == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n    ...,\n    featuredServices[]->{_id, title, slug, icon, shortDescription, whoItsFor},\n    featuredCaseStudy->{_id, client, slug, headline, resultLine, stats, photo, videoUrl, service->{title}},\n    testimonials[]->{_id, quote, name, role, company, avatar},\n    featuredIndustries[]->{_id, title, slug, icon, shortDescription, pageBuilt}\n  }': HOME_PAGE_QUERY_RESULT;
    '*[_type == "servicesLandingPage"][0]{\n    ...,\n    serviceCards[]{\n      ...,\n      service->{_id, title, slug, category, icon, shortDescription, whoItsFor}\n    },\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},\n    testimonial->{_id, quote, name, role, company}\n  }': SERVICES_LANDING_QUERY_RESULT;
    '*[_type == "aboutPage"][0]{\n    ...,\n    team[]->{_id, name, role, pronouns, photo, bio, outsideWork, skills, favouriteHubSpotFeature, whyTheyLoveHubSpot, linkedIn},\n    testimonials[]->{_id, quote, name, role, company, avatar}\n  }': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "contactPage"][0]': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "blogPost"] | order(publishedAt desc)[0...3]{\n    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n    hubs[]->{name}\n  }': LATEST_POSTS_QUERY_RESULT;
    '*[_type == "service" && defined(slug.current)].slug.current': SERVICE_SLUGS_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n    ...,\n    pricingTable->{confirmed, tiers, fallbackText},\n    caseStudy->{_id, client, slug, headline, resultLine, photo, status},\n    testimonial->{_id, quote, name, role, company, avatar},\n    relatedServices[]->{_id, title, slug, icon, shortDescription}\n  }': SERVICE_QUERY_RESULT;
    '*[_type == "solutionsPage"][0]{\n    ...,\n    relatedCaseStudy->{_id, client, slug, headline, resultLine, photo, status, service->{title}}\n  }': SOLUTIONS_PAGE_QUERY_RESULT;
    '*[_type == "hubOffering"] | order(order asc){\n    _id, name, eyebrow, description, icon, isFeatured,\n    linkedService->{title, slug}\n  }': HUB_OFFERINGS_QUERY_RESULT;
    '*[_type == "industriesHubPage"][0]{\n    ...,\n    industries[]->{_id, title, slug, icon, shortDescription, pageBuilt},\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, industry->{title}}\n  }': INDUSTRIES_HUB_QUERY_RESULT;
    '*[_type == "industry" && defined(slug.current)].slug.current': INDUSTRY_SLUGS_QUERY_RESULT;
    '*[_type == "industry" && slug.current == $slug][0]{\n    ...,\n    caseStudy->{_id, client, slug, headline, resultLine, photo, status},\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': INDUSTRY_QUERY_RESULT;
    '*[_type == "ourWorkPage"][0]{\n    ...,\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},\n    videoTestimonials[]->{_id, quote, name, company, videoUrl, videoStill},\n    googleReviews[]->{_id, quote, name, company}\n  }': OUR_WORK_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current)].slug.current': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[_type == "caseStudy" && slug.current == $slug][0]{\n    ...,\n    service->{title, slug},\n    industry->{title, slug},\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': CASE_STUDY_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current) && slug.current != $slug]\n    | order(status desc, client asc)[0...3]{\n      _id, client, slug, resultLine, photo, status, service->{title}\n    }': RELATED_CASE_STUDIES_QUERY_RESULT;
    '*[_type == "insightHubPage"][0]{\n    ...,\n    featuredPost->{\n      _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n      hubs[]->{name}, author->{name, photo}\n    }\n  }': INSIGHT_HUB_QUERY_RESULT;
    '*[_type == "blogPost"] | order(publishedAt desc){\n    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n    hubs[]->{name}\n  }': ALL_POSTS_QUERY_RESULT;
    '*[_type == "blogPost" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
    '{\n    "page": *[_type == "eventsPage"][0],\n    "upcoming": *[_type == "event" && startDateTime >= now()] | order(startDateTime asc){\n      \n  _id, title, slug, categories, startDateTime, endDateTime, venueType,\n  shortLocation, shortDescription, cardImage, capacity, spotsRemaining\n\n    },\n    "past": *[_type == "event" && startDateTime < now()] | order(startDateTime desc)[0...5]{\n      \n  _id, title, slug, categories, startDateTime, endDateTime, venueType,\n  shortLocation, shortDescription, cardImage, capacity, spotsRemaining\n,\n      recap->{title, slug}\n    }\n  }': EVENTS_PAGE_QUERY_RESULT;
    '*[_type == "event" && defined(slug.current)].slug.current': EVENT_SLUGS_QUERY_RESULT;
    '{\n    "event": *[_type == "event" && slug.current == $slug][0]{\n      ...,\n      host->{name, role, photo, linkedIn},\n      recap->{title, slug}\n    },\n    "others": *[_type == "event" && slug.current != $slug && startDateTime >= now()]\n      | order(startDateTime asc)[0...2]{ \n  _id, title, slug, categories, startDateTime, endDateTime, venueType,\n  shortLocation, shortDescription, cardImage, capacity, spotsRemaining\n }\n  }': EVENT_QUERY_RESULT;
    '*[_type == "resource"] | order(order asc){\n    _id, title, slug, summaryBullets, updatedAt, readTimeMinutes,\n    landingPageHref, category,\n    "fileUrl": fileAsset.asset->url,\n    author->{name, photo},\n    relatedPost->{title, slug}\n  }': RESOURCES_QUERY_RESULT;
    '*[_type == "legalPage" && slug.current == $slug][0]': LEGAL_PAGE_QUERY_RESULT;
    '*[_type == "partnerIntegration" && slug.current == $slug][0]{\n    ...,\n    caseStudy->{_id, client, slug, headline, resultLine, photo, status},\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': PARTNER_INTEGRATION_QUERY_RESULT;
    '*[_type == "partnerIntegration" && defined(slug.current)].slug.current': PARTNER_INTEGRATION_SLUGS_QUERY_RESULT;
    '*[_type == "blogPost" && slug.current == $slug][0]{\n    ...,\n    hubs[]->{name},\n    author->{name, role, photo},\n    "related": *[_type == "blogPost" && slug.current != $slug] | order(publishedAt desc)[0...3]{\n      _id, title, slug, topic, coverImage, publishedAt, readTime\n    }\n  }': POST_QUERY_RESULT;
    '*[_type == "careersPage"][0]{\n    ...,\n    "openRoles": *[_type == "vacancy" && status == "open" && defined(slug.current)]\n      | order(publishedAt desc){\n        _id, title, slug, summary, workArrangement, employmentType, location, department\n      }\n  }': CAREERS_PAGE_QUERY_RESULT;
    '*[_type == "vacancy" && slug.current == $slug][0]{\n    ...,\n    "sharedBenefits": *[_type == "careersPage"][0].benefits,\n    "teamPhoto": *[_type == "careersPage"][0].teamPhoto,\n    "registerInterest": *[_type == "careersPage"][0].registerInterest,\n    "related": *[_type == "vacancy" && status == "open" && slug.current != $slug]\n      | order(publishedAt desc)[0...3]{\n        _id, title, slug, summary, workArrangement, employmentType, location\n      }\n  }': VACANCY_QUERY_RESULT;
    '*[_type == "vacancy" && defined(slug.current)].slug.current': VACANCY_SLUGS_QUERY_RESULT;
    '*[_type == "vacancy" && status == "open" && defined(slug.current)]{\n    "slug": slug.current, _updatedAt\n  }': OPEN_VACANCY_SLUGS_QUERY_RESULT;
    '*[_type == "landingPage" && slug.current == $slug][0]{\n    ...,\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': LANDING_PAGE_QUERY_RESULT;
    '*[_type == "landingPage" && defined(slug.current)].slug.current': LANDING_PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "landingPage" && defined(slug.current) && pageBuilt == true]{\n    "slug": slug.current, _updatedAt\n  }': BUILT_LANDING_PAGES_QUERY_RESULT;
    '*[_type == "popup" && enabled == true]|order(_updatedAt desc)[0]{\n    _id, heading, body, mode, buttonLabel, ctaHref, successMessage,\n    triggerType, triggerSeconds, triggerPercent, showAgainAfterDays,\n    includePaths, excludePaths,\n    "imageUrl": image.asset->url,\n    "imageAlt": image.alt\n  }': POPUP_QUERY_RESULT;
  }
}
