/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail: string;
  contactPhone?: string;
  address?: string;
  meetingsUrl: string;
  linkedInUrl?: string;
  instagramUrl?: string;
  youTubeUrl?: string;
  googleReviewCount?: number;
  hubspotReviewCount?: number;
  newsletterHeading?: string;
  defaultSeo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  intro?: BlockContent;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type CtaBanner = {
  _type: "ctaBanner";
  heading: string;
  text?: string;
  button: Link;
  showMeetingsEmbed?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "figure";
      _key: string;
    }
>;

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading: string;
  emphasisPhrase?: string;
  markerStyle?: "circle" | "underline" | "none";
  subheading?: string;
  image?: ImageWithAlt;
  primaryCta?: Link;
  secondaryCta?: Link;
};

export type CareersPage = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  intro?: BlockContent;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  formHeading?: string;
  formOptions?: Array<string>;
  successHeading?: string;
  successText?: string;
  detailsHeading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type InsightHubPage = {
  _id: string;
  _type: "insightHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  featuredPost?: BlogPostReference;
  resourcesHeading?: string;
  resources?: Array<{
    title: string;
    link?: Link;
    _type: "resourceCard";
    _key: string;
  }>;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type OurWorkPage = {
  _id: string;
  _type: "ourWorkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  videoTestimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  googleReviews?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  googleReviewsUrl?: string;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type IndustriesHubPage = {
  _id: string;
  _type: "industriesHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  industries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  whyHeading?: string;
  whyItems?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustPillars?: Array<{
    heading: string;
    text: string;
    image?: ImageWithAlt;
    _type: "pillarRow";
    _key: string;
  }>;
  teamHeading?: string;
  team?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  culturePhotos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  cultureText?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  clientLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  storyHeading?: string;
  storyBody?: BlockContent;
  storyImage?: ImageWithAlt;
  lovePillars?: Array<
    {
      _key: string;
    } & IconCard
  >;
  values?: Array<
    {
      _key: string;
    } & IconCard
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type SolutionsPage = {
  _id: string;
  _type: "solutionsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  carouselHeading?: string;
  carouselIntro?: string;
  optimiseHeading?: string;
  optimiseIntro?: string;
  optimiseCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  relatedCaseStudy?: CaseStudyReference;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ServicesLandingPage = {
  _id: string;
  _type: "servicesLandingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  serviceCards?: Array<{
    service: ServiceReference;
    titleOverride?: string;
    descriptionOverride?: string;
    categoryOverride?: "discover" | "build" | "scale";
    anchor?: string;
    _type: "serviceCard";
    _key: string;
  }>;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  featuredCaseStudy?: CaseStudyReference;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  featuredIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body: BlockContent;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  location?: string;
  description?: string;
  registrationUrl?: string;
  image?: ImageWithAlt;
};

export type PartnerIntegration = {
  _id: string;
  _type: "partnerIntegration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  hero: Hero;
  whatItDoes?: BlockContent;
  whatWeSetUp?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudy?: CaseStudyReference;
  testimonial?: TestimonialReference;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type HubOffering = {
  _id: string;
  _type: "hubOffering";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  eyebrow: string;
  description: string;
  icon?: string;
  linkedService: ServiceReference;
  isFeatured?: boolean;
  order: number;
};

export type HubOfferingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hubOffering";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  topic:
    | "feature-spotlights"
    | "best-practices"
    | "news-and-events"
    | "our-approach"
    | "ai-developments";
  hubs?: Array<
    {
      _key: string;
    } & HubOfferingReference
  >;
  author: TeamMemberReference;
  publishedAt: string;
  readTime: number;
  excerpt: string;
  coverImage: ImageWithAlt;
  dek?: string;
  shortVersion?: Array<string>;
  body: BlockContent;
  seo?: Seo;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  photo?: ImageWithAlt;
  bio?: string;
  outsideWork?: string;
  skills?: Array<string>;
  favouriteHubSpotFeature?: string;
  whyTheyLoveHubSpot?: string;
  linkedIn?: string;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "discover" | "build" | "scale";
  icon?: string;
  shortDescription: string;
  whoItsFor?: string;
  hero: Hero;
  heroMeta?: string;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  painPointsCloser?: string;
  processSteps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  pricing?: Pricing;
  caseStudy?: CaseStudyReference;
  proofStat?: Stat;
  testimonial?: TestimonialReference;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type Stat = {
  _type: "stat";
  value: string;
  label: string;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: string;
  slug: Slug;
  status: "live" | "comingSoon";
  service: ServiceReference;
  industry?: IndustryReference;
  headline: string;
  resultLine?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  photo?: ImageWithAlt;
  videoUrl?: string;
  testimonial?: TestimonialReference;
  body?: BlockContent;
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  icon?: string;
  shortDescription: string;
  pageBuilt?: boolean;
  hero?: Hero;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  howWeFixHeading?: string;
  howWeFixBody?: BlockContent;
  checklist?: Array<string>;
  caseStudy?: CaseStudyReference;
  proofStat?: Stat;
  testimonial?: TestimonialReference;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  role?: string;
  company: string;
  avatar?: ImageWithAlt;
  source?: "direct" | "google" | "hubspot";
  videoUrl?: string;
  videoStill?: ImageWithAlt;
};

export type Pricing = {
  _type: "pricing";
  confirmed?: boolean;
  tiers?: Array<
    {
      _key: string;
    } & PricingTier
  >;
  fallbackText?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type IconCard = {
  _type: "iconCard";
  title: string;
  text: string;
  icon?: string;
};

export type PricingTier = {
  _type: "pricingTier";
  name: string;
  description?: string;
  price: number;
  priceSuffix?: string;
  features: Array<string>;
  ctaLabel?: string;
  featured?: boolean;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | Seo
  | EventsPage
  | CtaBanner
  | BlockContent
  | Hero
  | CareersPage
  | ContactPage
  | BlogPostReference
  | InsightHubPage
  | Link
  | CaseStudyReference
  | TestimonialReference
  | OurWorkPage
  | IndustryReference
  | IndustriesHubPage
  | TeamMemberReference
  | AboutPage
  | ImageWithAlt
  | SolutionsPage
  | ServiceReference
  | ServicesLandingPage
  | HomePage
  | LegalPage
  | Slug
  | Event
  | PartnerIntegration
  | HubOffering
  | HubOfferingReference
  | BlogPost
  | TeamMember
  | Service
  | Stat
  | CaseStudy
  | Industry
  | Testimonial
  | Pricing
  | SanityImageCrop
  | SanityImageHotspot
  | IconCard
  | PricingTier
  | FaqItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/app/sitemap.ts
// Variable: SITEMAP_QUERY
// Query: {    "services": *[_type == "service" && defined(slug.current)]{ "slug": slug.current, _updatedAt },    "industries": *[_type == "industry" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },    "caseStudies": *[_type == "caseStudy" && defined(slug.current) && status == "live"]{ "slug": slug.current, _updatedAt },    "posts": *[_type == "blogPost" && defined(slug.current)]{ "slug": slug.current, _updatedAt }  }
export type SITEMAP_QUERY_RESULT = {
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  industries: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  caseStudies: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Source: ../web/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail: string;
  contactPhone?: string;
  address?: string;
  meetingsUrl: string;
  linkedInUrl?: string;
  instagramUrl?: string;
  youTubeUrl?: string;
  googleReviewCount?: number;
  hubspotReviewCount?: number;
  newsletterHeading?: string;
  defaultSeo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    ...,    featuredServices[]->{_id, title, slug, icon, shortDescription, whoItsFor},    featuredCaseStudy->{_id, client, slug, headline, resultLine, stats, photo, videoUrl, service->{title}},    testimonials[]->{_id, quote, name, role, company, avatar},    featuredIndustries[]->{_id, title, slug, icon, shortDescription, pageBuilt}  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  featuredServices: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    whoItsFor: string | null;
  }> | null;
  featuredCaseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    stats: Array<
      {
        _key: string;
      } & Stat
    > | null;
    photo: ImageWithAlt | null;
    videoUrl: string | null;
    service: {
      title: string;
    };
  } | null;
  testimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  }> | null;
  featuredIndustries: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    pageBuilt: boolean | null;
  }> | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: SERVICES_LANDING_QUERY
// Query: *[_type == "servicesLandingPage"][0]{    ...,    serviceCards[]{      ...,      service->{_id, title, slug, category, icon, shortDescription, whoItsFor}    },    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}}  }
export type SERVICES_LANDING_QUERY_RESULT = {
  _id: string;
  _type: "servicesLandingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  serviceCards: Array<{
    service: {
      _id: string;
      title: string;
      slug: Slug;
      category: "build" | "discover" | "scale";
      icon: string | null;
      shortDescription: string;
      whoItsFor: string | null;
    };
    titleOverride?: string;
    descriptionOverride?: string;
    categoryOverride?: "build" | "discover" | "scale";
    anchor?: string;
    _type: "serviceCard";
    _key: string;
  }> | null;
  whyHeading?: string;
  whyCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  }> | null;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    ...,    team[]->{_id, name, role, photo, bio, outsideWork, skills, favouriteHubSpotFeature, whyTheyLoveHubSpot, linkedIn},    testimonials[]->{_id, quote, name, role, company, avatar}  }
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  trustPillars?: Array<{
    heading: string;
    text: string;
    image?: ImageWithAlt;
    _type: "pillarRow";
    _key: string;
  }>;
  teamHeading?: string;
  team: Array<{
    _id: string;
    name: string;
    role: string;
    photo: ImageWithAlt | null;
    bio: string | null;
    outsideWork: string | null;
    skills: Array<string> | null;
    favouriteHubSpotFeature: string | null;
    whyTheyLoveHubSpot: string | null;
    linkedIn: string | null;
  }> | null;
  culturePhotos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  cultureText?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  testimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  }> | null;
  clientLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  storyHeading?: string;
  storyBody?: BlockContent;
  storyImage?: ImageWithAlt;
  lovePillars?: Array<
    {
      _key: string;
    } & IconCard
  >;
  values?: Array<
    {
      _key: string;
    } & IconCard
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  formHeading?: string;
  formOptions?: Array<string>;
  successHeading?: string;
  successText?: string;
  detailsHeading?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc)[0...3]{    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,    hubs[]->{name}  }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  excerpt: string;
  coverImage: ImageWithAlt;
  publishedAt: string;
  readTime: number;
  hubs: Array<{
    name: string;
  }> | null;
}>;

// Source: ../web/sanity/queries.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service" && defined(slug.current)].slug.current
export type SERVICE_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    ...,    caseStudy->{_id, client, slug, headline, resultLine, photo, status},    testimonial->{_id, quote, name, role, company, avatar},    relatedServices[]->{_id, title, slug, icon, shortDescription}  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "build" | "discover" | "scale";
  icon?: string;
  shortDescription: string;
  whoItsFor?: string;
  hero: Hero;
  heroMeta?: string;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  painPointsCloser?: string;
  processSteps?: Array<
    {
      _key: string;
    } & IconCard
  >;
  pricing?: Pricing;
  caseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
  } | null;
  proofStat?: Stat;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  relatedServices: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
  }> | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: SOLUTIONS_PAGE_QUERY
// Query: *[_type == "solutionsPage"][0]{    ...,    relatedCaseStudy->{_id, client, slug, headline, resultLine, photo, status, service->{title}}  }
export type SOLUTIONS_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "solutionsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  carouselHeading?: string;
  carouselIntro?: string;
  optimiseHeading?: string;
  optimiseIntro?: string;
  optimiseCards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  relatedCaseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  } | null;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: HUB_OFFERINGS_QUERY
// Query: *[_type == "hubOffering"] | order(order asc){    _id, name, eyebrow, description, icon, isFeatured,    linkedService->{title, slug}  }
export type HUB_OFFERINGS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  eyebrow: string;
  description: string;
  icon: string | null;
  isFeatured: boolean | null;
  linkedService: {
    title: string;
    slug: Slug;
  };
}>;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRIES_HUB_QUERY
// Query: *[_type == "industriesHubPage"][0]{    ...,    industries[]->{_id, title, slug, icon, shortDescription, pageBuilt},    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, industry->{title}}  }
export type INDUSTRIES_HUB_QUERY_RESULT = {
  _id: string;
  _type: "industriesHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  gridHeading?: string;
  gridIntro?: string;
  industries: Array<{
    _id: string;
    title: string;
    slug: Slug;
    icon: string | null;
    shortDescription: string;
    pageBuilt: boolean | null;
  }> | null;
  whyHeading?: string;
  whyItems?: Array<
    {
      _key: string;
    } & IconCard
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    industry: {
      title: string;
    } | null;
  }> | null;
  trustLogos?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRY_SLUGS_QUERY
// Query: *[_type == "industry" && defined(slug.current)].slug.current
export type INDUSTRY_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: INDUSTRY_QUERY
// Query: *[_type == "industry" && slug.current == $slug][0]{    ...,    caseStudy->{_id, client, slug, headline, resultLine, photo, status},    testimonial->{_id, quote, name, role, company, avatar}  }
export type INDUSTRY_QUERY_RESULT = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  icon?: string;
  shortDescription: string;
  pageBuilt?: boolean;
  hero?: Hero;
  painPoints?: Array<
    {
      _key: string;
    } & IconCard
  >;
  howWeFixHeading?: string;
  howWeFixBody?: BlockContent;
  checklist?: Array<string>;
  caseStudy: {
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
  } | null;
  proofStat?: Stat;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: OUR_WORK_QUERY
// Query: *[_type == "ourWorkPage"][0]{    ...,    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},    videoTestimonials[]->{_id, quote, name, company, videoUrl, videoStill},    googleReviews[]->{_id, quote, name, company}  }
export type OUR_WORK_QUERY_RESULT = {
  _id: string;
  _type: "ourWorkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  caseStudies: Array<{
    _id: string;
    client: string;
    slug: Slug;
    headline: string;
    resultLine: string | null;
    photo: ImageWithAlt | null;
    status: "comingSoon" | "live";
    service: {
      title: string;
    };
  }> | null;
  videoTestimonials: Array<{
    _id: string;
    quote: string;
    name: string;
    company: string;
    videoUrl: string | null;
    videoStill: ImageWithAlt | null;
  }> | null;
  googleReviews: Array<{
    _id: string;
    quote: string;
    name: string;
    company: string;
  }> | null;
  googleReviewsUrl?: string;
  ctaBanner?: CtaBanner;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    ...,    service->{title, slug},    industry->{title, slug},    testimonial->{_id, quote, name, role, company, avatar}  }
export type CASE_STUDY_QUERY_RESULT = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: string;
  slug: Slug;
  status: "comingSoon" | "live";
  service: {
    title: string;
    slug: Slug;
  };
  industry: {
    title: string;
    slug: Slug;
  } | null;
  headline: string;
  resultLine?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  photo?: ImageWithAlt;
  videoUrl?: string;
  testimonial: {
    _id: string;
    quote: string;
    name: string;
    role: string | null;
    company: string;
    avatar: ImageWithAlt | null;
  } | null;
  body?: BlockContent;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: INSIGHT_HUB_QUERY
// Query: *[_type == "insightHubPage"][0]{    ...,    featuredPost->{      _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,      hubs[]->{name}, author->{name, photo}    }  }
export type INSIGHT_HUB_QUERY_RESULT = {
  _id: string;
  _type: "insightHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: Hero;
  featuredPost: {
    _id: string;
    title: string;
    slug: Slug;
    topic:
      | "ai-developments"
      | "best-practices"
      | "feature-spotlights"
      | "news-and-events"
      | "our-approach";
    excerpt: string;
    coverImage: ImageWithAlt;
    publishedAt: string;
    readTime: number;
    hubs: Array<{
      name: string;
    }> | null;
    author: {
      name: string;
      photo: ImageWithAlt | null;
    };
  } | null;
  resourcesHeading?: string;
  resources?: Array<{
    title: string;
    link?: Link;
    _type: "resourceCard";
    _key: string;
  }>;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
} | null;

// Source: ../web/sanity/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(publishedAt desc){    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,    hubs[]->{name}  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  excerpt: string;
  coverImage: ImageWithAlt;
  publishedAt: string;
  readTime: number;
  hubs: Array<{
    name: string;
  }> | null;
}>;

// Source: ../web/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0]{    ...,    hubs[]->{name},    author->{name, role, photo},    "related": *[_type == "blogPost" && slug.current != $slug] | order(publishedAt desc)[0...3]{      _id, title, slug, topic, coverImage, publishedAt, readTime    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  topic:
    | "ai-developments"
    | "best-practices"
    | "feature-spotlights"
    | "news-and-events"
    | "our-approach";
  hubs: Array<{
    name: string;
  }> | null;
  author: {
    name: string;
    role: string;
    photo: ImageWithAlt | null;
  };
  publishedAt: string;
  readTime: number;
  excerpt: string;
  coverImage: ImageWithAlt;
  dek?: string;
  shortVersion?: Array<string>;
  body: BlockContent;
  seo?: Seo;
  related: Array<{
    _id: string;
    title: string;
    slug: Slug;
    topic:
      | "ai-developments"
      | "best-practices"
      | "feature-spotlights"
      | "news-and-events"
      | "our-approach";
    coverImage: ImageWithAlt;
    publishedAt: string;
    readTime: number;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n    "services": *[_type == "service" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n    "industries": *[_type == "industry" && defined(slug.current) && pageBuilt == true]{ "slug": slug.current, _updatedAt },\n    "caseStudies": *[_type == "caseStudy" && defined(slug.current) && status == "live"]{ "slug": slug.current, _updatedAt },\n    "posts": *[_type == "blogPost" && defined(slug.current)]{ "slug": slug.current, _updatedAt }\n  }': SITEMAP_QUERY_RESULT;
    '*[_type == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n    ...,\n    featuredServices[]->{_id, title, slug, icon, shortDescription, whoItsFor},\n    featuredCaseStudy->{_id, client, slug, headline, resultLine, stats, photo, videoUrl, service->{title}},\n    testimonials[]->{_id, quote, name, role, company, avatar},\n    featuredIndustries[]->{_id, title, slug, icon, shortDescription, pageBuilt}\n  }': HOME_PAGE_QUERY_RESULT;
    '*[_type == "servicesLandingPage"][0]{\n    ...,\n    serviceCards[]{\n      ...,\n      service->{_id, title, slug, category, icon, shortDescription, whoItsFor}\n    },\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}}\n  }': SERVICES_LANDING_QUERY_RESULT;
    '*[_type == "aboutPage"][0]{\n    ...,\n    team[]->{_id, name, role, photo, bio, outsideWork, skills, favouriteHubSpotFeature, whyTheyLoveHubSpot, linkedIn},\n    testimonials[]->{_id, quote, name, role, company, avatar}\n  }': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "contactPage"][0]': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "blogPost"] | order(publishedAt desc)[0...3]{\n    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n    hubs[]->{name}\n  }': LATEST_POSTS_QUERY_RESULT;
    '*[_type == "service" && defined(slug.current)].slug.current': SERVICE_SLUGS_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n    ...,\n    caseStudy->{_id, client, slug, headline, resultLine, photo, status},\n    testimonial->{_id, quote, name, role, company, avatar},\n    relatedServices[]->{_id, title, slug, icon, shortDescription}\n  }': SERVICE_QUERY_RESULT;
    '*[_type == "solutionsPage"][0]{\n    ...,\n    relatedCaseStudy->{_id, client, slug, headline, resultLine, photo, status, service->{title}}\n  }': SOLUTIONS_PAGE_QUERY_RESULT;
    '*[_type == "hubOffering"] | order(order asc){\n    _id, name, eyebrow, description, icon, isFeatured,\n    linkedService->{title, slug}\n  }': HUB_OFFERINGS_QUERY_RESULT;
    '*[_type == "industriesHubPage"][0]{\n    ...,\n    industries[]->{_id, title, slug, icon, shortDescription, pageBuilt},\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, industry->{title}}\n  }': INDUSTRIES_HUB_QUERY_RESULT;
    '*[_type == "industry" && defined(slug.current)].slug.current': INDUSTRY_SLUGS_QUERY_RESULT;
    '*[_type == "industry" && slug.current == $slug][0]{\n    ...,\n    caseStudy->{_id, client, slug, headline, resultLine, photo, status},\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': INDUSTRY_QUERY_RESULT;
    '*[_type == "ourWorkPage"][0]{\n    ...,\n    caseStudies[]->{_id, client, slug, headline, resultLine, photo, status, service->{title}},\n    videoTestimonials[]->{_id, quote, name, company, videoUrl, videoStill},\n    googleReviews[]->{_id, quote, name, company}\n  }': OUR_WORK_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current)].slug.current': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[_type == "caseStudy" && slug.current == $slug][0]{\n    ...,\n    service->{title, slug},\n    industry->{title, slug},\n    testimonial->{_id, quote, name, role, company, avatar}\n  }': CASE_STUDY_QUERY_RESULT;
    '*[_type == "insightHubPage"][0]{\n    ...,\n    featuredPost->{\n      _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n      hubs[]->{name}, author->{name, photo}\n    }\n  }': INSIGHT_HUB_QUERY_RESULT;
    '*[_type == "blogPost"] | order(publishedAt desc){\n    _id, title, slug, topic, excerpt, coverImage, publishedAt, readTime,\n    hubs[]->{name}\n  }': ALL_POSTS_QUERY_RESULT;
    '*[_type == "blogPost" && defined(slug.current)].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "blogPost" && slug.current == $slug][0]{\n    ...,\n    hubs[]->{name},\n    author->{name, role, photo},\n    "related": *[_type == "blogPost" && slug.current != $slug] | order(publishedAt desc)[0...3]{\n      _id, title, slug, topic, coverImage, publishedAt, readTime\n    }\n  }': POST_QUERY_RESULT;
  }
}
