import {defineArrayMember, defineField, defineType} from 'sanity'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About page',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'hero',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'trustPillars',
      title: '"Why you\'ll trust us" rows',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({
          name: 'pillarRow',
          title: 'Row',
          type: 'object',
          fields: [
            defineField({
              name: 'heading',
              title: 'Heading',
              type: 'string',
              validation: (rule) => rule.required().max(80),
            }),
            defineField({
              name: 'text',
              title: 'Text',
              type: 'text',
              rows: 3,
              validation: (rule) => rule.required().max(500),
            }),
            defineField({name: 'image', title: 'Image', type: 'imageWithAlt'}),
          ],
          preview: {select: {title: 'heading'}},
        }),
      ],
      validation: (rule) => rule.max(2),
    }),
    defineField({
      name: 'teamHeading',
      title: 'Team section heading',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: 'team',
      title: 'Team members',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'teamMember'}]})],
      validation: (rule) => rule.max(6).unique(),
    }),
    defineField({
      name: 'culturePhotos',
      title: 'Culture photo strip',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'imageWithAlt'})],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: 'cultureText',
      title: 'Culture copy',
      type: 'text',
      rows: 4,
      group: 'content',
      validation: (rule) => rule.max(700),
    }),
    defineField({
      name: 'stats',
      title: 'Stats',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'stat'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: 'testimonials',
      title: 'Testimonial carousel',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'testimonial'}]})],
      validation: (rule) => rule.max(5).unique(),
    }),
    defineField({
      name: 'clientLogos',
      title: 'Client logos',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'imageWithAlt'})],
      description: 'Only logos with display permission',
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: 'storyHeading',
      title: 'Founding story heading',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: 'storyBody',
      title: 'Founding story',
      type: 'blockContent',
      group: 'content',
    }),
    defineField({
      name: 'storyImage',
      title: 'Founding story image',
      type: 'imageWithAlt',
      group: 'content',
    }),
    defineField({
      name: 'lovePillars',
      title: '"Why you\'ll love us" columns',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: 'values',
      title: 'Values cards',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({name: 'ctaBanner', title: 'CTA banner', type: 'ctaBanner', group: 'content'}),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'About page'})},
})
