import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Home page',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'hero',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'trustLogos',
      title: 'Trust bar client logos',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'imageWithAlt'})],
      description: 'Only logos with display permission',
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: 'whyHeading',
      title: '"Why Zippily" heading',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: 'whyCards',
      title: '"Why Zippily" value cards',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: 'featuredServices',
      title: 'Services teaser',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})],
      validation: (rule) => rule.max(4).unique(),
    }),
    defineField({
      name: 'featuredCaseStudy',
      title: 'Featured case study',
      type: 'reference',
      group: 'content',
      to: [{type: 'caseStudy'}],
    }),
    defineField({
      name: 'testimonials',
      title: 'Testimonials',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'testimonial'}]})],
      validation: (rule) => rule.max(3).unique(),
    }),
    defineField({
      name: 'featuredIndustries',
      title: 'Industries teaser',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'industry'}]})],
      description: 'Tracker industries only — the Insights teaser pulls the latest 3 posts automatically',
      validation: (rule) => rule.max(6).unique(),
    }),
    defineField({
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'faqItem'})],
      validation: (rule) => rule.max(5),
    }),
    defineField({
      name: 'ctaBanner',
      title: 'CTA banner',
      type: 'ctaBanner',
      group: 'content',
      description: 'Home uses the meetings embed variant',
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Home page'})},
})
