import {defineArrayMember, defineField, defineType} from 'sanity'
import {slugShape} from '../../lib/slugRules'
import {BLOG_TOPICS} from '../constants'

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog post',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'meta', title: 'Meta'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title'},
      description: 'URL: /insights/[slug]',
      validation: slugShape,
    }),
    defineField({
      name: 'topic',
      title: 'Topic',
      type: 'string',
      group: 'meta',
      options: {list: [...BLOG_TOPICS]},
      description: 'Drives the Topic filter on the Insight Hub',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'hubs',
      title: 'Related Hubs',
      type: 'array',
      group: 'meta',
      of: [defineArrayMember({type: 'reference', to: [{type: 'hubOffering'}]})],
      description: 'Drives the Hub filter and the Hub pills on cards',
      validation: (rule) => rule.max(3).unique(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      group: 'meta',
      to: [{type: 'teamMember'}],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'date',
      group: 'meta',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'readTime',
      title: 'Read time (minutes)',
      type: 'number',
      group: 'meta',
      validation: (rule) => rule.required().integer().min(1).max(60),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Used on cards and the featured-post slot',
      validation: (rule) => rule.required().max(300),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover image',
      type: 'imageWithAlt',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'dek',
      title: 'Standfirst',
      type: 'text',
      rows: 2,
      group: 'content',
      description: 'Intro line under the article H1',
      validation: (rule) => rule.max(240),
    }),
    defineField({
      name: 'shortVersion',
      title: '"The short version" bullets',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'string'})],
      description: 'The callout box at the top of the article (replaces a TOC)',
      validation: (rule) => rule.max(5),
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'blockContent',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  orderings: [
    {
      title: 'Published date, newest first',
      name: 'publishedAtDesc',
      by: [{field: 'publishedAt', direction: 'desc'}],
    },
  ],
  preview: {
    select: {title: 'title', subtitle: 'topic', media: 'coverImage'},
  },
})
