import {defineArrayMember, defineField, defineType} from 'sanity'
import {slugShape} from '../../lib/slugRules'

export const industry = defineType({
  name: 'industry',
  title: 'Industry',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'related', title: 'Related'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title'},
      description: 'URL: /industries/[slug]',
      validation: slugShape,
    }),
    defineField({
      name: 'icon',
      title: 'Icon name',
      type: 'string',
      group: 'content',
      description: 'Lucide icon name for hub cards and the hero badge',
      validation: (rule) => rule.max(40),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description (hub card)',
      type: 'text',
      rows: 2,
      group: 'content',
      validation: (rule) => rule.required().max(200),
    }),
    defineField({
      name: 'pageBuilt',
      title: 'Page is built',
      type: 'boolean',
      group: 'content',
      initialValue: false,
      description:
        'Off = the Industries hub card links to CRM Implementation instead of this page (tracker rule for not-yet-built industries)',
    }),
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'hero',
      group: 'content',
    }),
    defineField({
      name: 'painPoints',
      title: '"Sound familiar?" pain points',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: 'howWeFixHeading',
      title: '"How we fix it" heading',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: 'howWeFixBody',
      title: '"How we fix it" body',
      type: 'blockContent',
      group: 'content',
      description: 'Include an inline link to the most relevant service page',
    }),
    defineField({
      name: 'checklist',
      title: 'Checklist items',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'string'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: 'caseStudy',
      title: 'Proof case study',
      type: 'reference',
      group: 'related',
      to: [{type: 'caseStudy'}],
      description: 'Optional — the proof section is dropped entirely when empty (template rule)',
    }),
    defineField({
      name: 'proofStat',
      title: 'Proof stat',
      type: 'stat',
      group: 'related',
    }),
    defineField({
      name: 'testimonial',
      title: 'Testimonial',
      type: 'reference',
      group: 'related',
      to: [{type: 'testimonial'}],
      description: 'Optional — the testimonial section is dropped entirely when empty',
    }),
    defineField({
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'faqItem'})],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: 'ctaBanner',
      title: 'CTA banner',
      type: 'ctaBanner',
      group: 'content',
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {select: {title: 'title'}},
})
