import {defineArrayMember, defineField, defineType} from 'sanity'
import {slugShape} from '../../lib/slugRules'
import {SERVICE_CATEGORIES} from '../constants'

export const service = defineType({
  name: 'service',
  title: 'Service',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'pricing', title: 'Pricing'},
    {name: 'related', title: 'Related'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title'},
      description: 'URL: /services/[slug]',
      validation: slugShape,
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'content',
      options: {list: [...SERVICE_CATEGORIES], layout: 'radio'},
      description: 'Drives the Discover/Build/Scale filter on the Services landing page',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'icon',
      title: 'Icon name',
      type: 'string',
      group: 'content',
      description: 'Lucide icon name for cards',
      validation: (rule) => rule.max(40),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description (cards)',
      type: 'text',
      rows: 2,
      group: 'content',
      validation: (rule) => rule.required().max(200),
    }),
    defineField({
      name: 'whoItsFor',
      title: '"Who it\'s for" line (card hover)',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: 'pageBuilt',
      title: 'Page is built',
      type: 'boolean',
      group: 'content',
      initialValue: false,
      description:
        'Off = the page still holds placeholder copy: it is kept out of the sitemap and marked noindex, so unfinished wording can never be picked up by Google. Turn on once the real copy has landed.',
    }),
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'hero',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroMeta',
      title: 'Hero meta line',
      type: 'string',
      group: 'content',
      description: 'e.g. "From $7,500 · typically live in 4–6 weeks". Leave empty if pricing unconfirmed.',
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: 'introEyebrow',
      title: 'Intro eyebrow (small caps line above the intro heading)',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'introHeading',
      title: 'Intro heading',
      type: 'string',
      group: 'content',
      description: 'The bold line of the image-beside-text intro section',
    }),
    defineField({
      name: 'introBody',
      title: 'Intro body',
      type: 'text',
      rows: 6,
      group: 'content',
      description:
        'Plain text; a blank line starts a new paragraph. The intro section is hidden when this is empty.',
    }),
    defineField({
      name: 'introImage',
      title: 'Intro image (client + Zippily photo)',
      type: 'imageWithAlt',
      group: 'content',
    }),
    defineField({
      name: 'introImageSecond',
      title: 'Intro image 2 (retainer page renders two images side by side)',
      type: 'imageWithAlt',
      group: 'content',
    }),
    defineField({
      name: 'benefitsHeading',
      title: 'Benefits heading (the "Why retainers?" band)',
      type: 'string',
      group: 'content',
      description: 'Rendered on the bespoke RevOps retainers page; unused elsewhere for now',
    }),
    defineField({
      name: 'benefitsIntro',
      title: 'Benefits intro',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'benefits',
      title: 'Benefit points',
      type: 'array',
      group: 'content',
      validation: (rule) => rule.max(4),
      of: [
        defineArrayMember({
          type: 'object',
          name: 'benefitItem',
          fields: [
            defineField({name: 'heading', title: 'Heading', type: 'string'}),
            defineField({name: 'text', title: 'Text', type: 'text', rows: 3}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'proofHeading',
      title: 'Case study feature heading (retainer page)',
      type: 'string',
      group: 'related',
    }),
    defineField({
      name: 'proofBody',
      title: 'Case study feature body',
      type: 'text',
      rows: 4,
      group: 'related',
    }),
    defineField({
      name: 'painPoints',
      title: '"Is this you?" pain points',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: 'painPointsCloser',
      title: 'Pain points closing line',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.max(200),
    }),
    defineField({
      name: 'processSteps',
      title: 'Process steps',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'iconCard'})],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: 'pricingTable',
      title: 'Pricing table',
      type: 'reference',
      to: [{type: 'pricingTable'}],
      group: 'pricing',
      description:
        'The shared table this page renders. Managed under Pricing tables so a repricing round is one edit, not one per service.',
    }),
    defineField({
      name: 'pricing',
      title: 'Pricing (legacy inline)',
      type: 'pricing',
      group: 'pricing',
      description:
        'Only used when no pricing table is linked above. Kept so nothing broke during the move to shared tables.',
    }),
    defineField({
      name: 'caseStudy',
      title: 'Proof case study',
      type: 'reference',
      group: 'related',
      to: [{type: 'caseStudy'}],
    }),
    defineField({
      name: 'proofStat',
      title: 'Proof stat',
      type: 'stat',
      group: 'related',
      description: 'Big stat on the proof section (e.g. "3 weeks")',
    }),
    defineField({
      name: 'testimonial',
      title: 'Testimonial',
      type: 'reference',
      group: 'related',
      to: [{type: 'testimonial'}],
    }),
    defineField({
      name: 'relatedServices',
      title: 'Often paired with',
      type: 'array',
      group: 'related',
      of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})],
      validation: (rule) => rule.max(3).unique(),
    }),
    defineField({
      name: 'relatedPosts',
      title: 'Helpful resources (blog posts)',
      type: 'array',
      group: 'related',
      of: [{type: 'reference', to: [{type: 'blogPost'}]}],
      validation: (rule) => rule.max(3),
      description: 'The "Helpful resources" cards — hidden when empty',
    }),
    defineField({
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'faqItem'})],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: 'ctaBanner',
      title: 'CTA banner',
      type: 'ctaBanner',
      group: 'content',
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'category'},
  },
})
